site_name: Gambit-Framework Docs

nav:
  - Home: index.md
  - Getting Start:
    - Installation: getting_started/install.md
    - Starting the Teamserver: getting_started/server.md 
    - Connecting to the Teamserver: getting_started/connecting.md
  - User Interface:
    - Overview: ui/overview.md
  - Server Configuration:
    - Overview: server/overview.md
    - Server Profile: server/profile.md
  - User Management:
    - Overview: users/overview.md
  - Listener Management:
    - Overview: listener/overview.md
    - HTTP(s): listener/http.md
  - Evasive Features:
    - Overview: evasion/overview.md
    - Evasion Profile: evasion/profile.md
  - Pivoting:
    - Overview: pivoting/overview.md
  - Supporting Tools:
    - Overview: tools/overview.md
    - g2lint: tools/g2lint.md
    - g2sc: tools/g2sc.md
  - Updates:
    - Roadmap: updates/roadmap.md
    - v0.1.0: updates/v0.1.0.md

theme:
  name: readthedocs
  color_mode: auto
  user_color_mode_togglee: true